theme: jekyll-theme-cayman
url: https://sophrodri.github.io/
baseurl: /jk-assignment/
title: The Overdressed Diaries 
description: the fashion blog for the sometimes stressed, and always overdressed people with the passion for fashion. 
instagram: "http://instagram.com/the.overdressed.diaries"
author: Sophia Rodriguez 

